CREATE TABLE IF NOT EXISTS student (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(30),
    score DOUBLE,
    graduate BOOLEAN,
    create_date TIMESTAMP
);

CREATE TABLE IF NOT EXISTS department (
    departmentId INT PRIMARY KEY AUTO_INCREMENT,
    departmentName VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS Employee(
    EmployeeId INT PRIMARY KEY AUTO_INCREMENT,
    EmployeeName VARCHAR(30),
    department VARCHAR(30),
    dateOfJoining TIMESTAMP
);

CREATE SEQUENCE IF NOT EXISTS "department_seq" 
MINVALUE 1 
MAXVALUE 999999999 
INCREMENT BY 1 
START WITH 9001 
NOCACHE 
NOCYCLE;

CREATE SEQUENCE IF NOT EXISTS "employee_seq" 
MINVALUE 1 
MAXVALUE 999999999 
INCREMENT BY 1 
START WITH 10001 
NOCACHE 
NOCYCLE;